Fix: Updated Readme
mara-labs/mara-chain pull request #35
Opened 2022-11-24 11:11 UTC by Olanetsoft

Closes: #34 

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2022-11-24 17:07 UTC, blewater requested changes
Thx, a few changes.

2022-11-24 17:07 UTC, blewater commented on README.md
> +You will likely get this error message `jq not found` To fix this, run `brew install jq`.
Add install link for jq to include all OS.

2022-11-24 17:07 UTC, blewater commented on README.md
> +export PATH=$PATH:$(go env GOPATH)/bin
Optional, Is Windows popular with our audience? In that case, we should test the chain and include compatible a win command.

2022-11-24 17:07 UTC, blewater commented on README.md
>  ```
Remove, already mentioned in step 2.

2022-11-28 21:32 UTC, Olanetsoft commented on README.md
> +You will likely get this error message `jq not found` To fix this, run `brew install jq`.
Updated

2022-11-28 21:34 UTC, Olanetsoft commented on README.md
>  ```
Updated

2022-11-28 21:34 UTC, Olanetsoft commented on README.md
> +```
Updated.

2022-11-29 12:44 UTC, blewater requested changes
a couple of fixes and adding windows equivalent

2022-11-29 12:44 UTC, blewater commented on README.md
> +./init.sh
`init.bat` for windows

2022-11-29 12:44 UTC, blewater commented on README.md
> +which marad
add windows command

2022-11-29 12:44 UTC, blewater commented on README.md
> +export GOPATH=$(go env GOPATH)
add windows equivalent for path setting

2022-11-29 12:56 UTC, Olanetsoft commented on README.md
> +Download and install Go quickly with the steps described [here](Download and install Go quickly with the steps described here).
Updated; that was a wrong paste.

2022-11-29 12:56 UTC, Olanetsoft commented on README.md
> +You will likely get this error message `jq not found` To fix this, follow the [guide](https://stedolan.github.io/jq/download/) to install jq.
updated

2022-11-29 12:58 UTC, Olanetsoft commented on README.md
> +./init.sh
updated

2022-11-29 23:19 UTC, blewater requested changes
1 change to complete this.

2022-11-29 23:19 UTC, blewater commented on README.md
> +./init.bat
just plain `init.bat` the above won't run or, even better, remove it till we update Readme for windows.

2022-11-30 05:39 UTC, Olanetsoft commented on README.md
> +./init.bat
Updated

2022-11-30 15:45 UTC, blewater approved these changes
Thanks @Olanetsoft

2022-12-01 13:47 UTC, merged